# Generated by Django 3.2 on 2023-03-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=330)),
                ('color', models.CharField(max_length=130)),
                ('price', models.FloatField()),
                ('region', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='gallery/%Y:%m:%d')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user')),
            ],
        ),
    ]
