# Generated by Django 3.2 on 2023-03-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='featured',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to='gallery/%Y:%m:%d'),
        ),
    ]
