# Generated by Django 3.2 on 2023-03-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to='products/%Y:%m:%d'),
        ),
    ]
